---
- import_playbook: ruby-playbook.yml
-
  hosts: all
  become: true
  become_user: root
  tasks:
    - import_tasks: base-packages-tasks.yml
    - import_tasks: redis-tasks.yml
    - import_tasks: nginx-tasks.yml
    - import_tasks: banner-tasks.yml
    - import_tasks: checkout-app.yml
    # - import_tasks: elasticsearch-tasks.yml
    #   vars:
    #     elastic_version: 5.6.3
    #     elastic_jvm_size: 500m
