---
-
  hosts: all
  roles:
    -
      role: rvm_io.ruby
      rvm1_install_flags: --auto-dotfiles
      rvm1_install_path: /usr/local/rvm
      rvm1_rubies:
        - ruby-{{ruby_version}}
      # was erroring on rvm update. Something about the GPG key
      rvm1_rvm_check_for_updates: false
      rvm1_user: root
      tags: ruby
  vars:
    ruby_version: 2.3.4
-
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
    - name: EPEL
      yum:
        name: epel-release
        state: latest
    - name: bug fix for libselinux-python error when copying files
      yum:
        name: libselinux-python
        state: latest
    - name: Download redis server
      unarchive:
        src: http://download.redis.io/redis-stable.tar.gz
        dest: /usr/local/share
        remote_src: true
    - name: Redis makefile
      make:
        chdir: /usr/local/share/redis-stable
    - name: redis install commands into path
      make:
        chdir: /usr/local/share/redis-stable
        target: install

