---
- import_playbook: ruby-playbook.yml
-
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
    - name: EPEL
      yum:
        name: epel-release
        state: latest
    - name: bug fix for libselinux-python error when copying files
      yum:
        name: libselinux-python
        state: latest
    - name: install Java version 8
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: correct java version selected
      alternatives:
        name: java
        path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
    - import_tasks: redis-tasks.yml
    - import_tasks: elasticsearch-tasks.yml
